# 端口号
server:
  port: 8763
  servlet:
    context-path: /rubbish-provider

spring:
  application:
    name: rubbish-cloud-provider

# eureka配置 客户端配置，注册到服务中心
eureka:
  client:
    service-url:
      #      defaultZone: http://10.10.65.93:9527/eureka/
      defaultZone: http://127.0.0.1:8762/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
