spring:
  application:
    name: rubbish-cloud-consumer
server:
  port: 8282
  servlet:
    context-path: /rubbish-cloud-consumer
logging:
  level:
    com.chrysalis2h.consumer.client: debug

# 启用hystrix配置
feign:
  hystrix:
    enabled: true
hystrix:
  dashboard:
    proxy-stream-allow-list: "localhost"