spring:
  application:
    name: rubbish-cloud-provider
server:
  port: 8181

# eureka配置 客户端配置，注册到服务中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true